#!/usr/bin/env python

import curses
import curses.wrapper
import sys

from cursedmaze import MazeWalker

# The size of a room in characters described as (width, height)
ROOM_SIZE = (4, 3)


def wrapped_main(win):
    # Create a maze walker
    my, mx = win.getmaxyx()
    walker = MazeWalker(
        width = mx // ROOM_SIZE[0],
        height = my // ROOM_SIZE[1])


def main():
    curses.wrapper(wrapped_main)


if __name__ == '__main__':
    main()
